version: '3'

services:
  backend:
    build: ./BACKEND
    container_name: backend
    ports:
      - "5001:5001"

  frontend:
    build: ./FRONTEND
    container_name: frontend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5001/api
      - REACT_APP_API_LOGIN="admin"
      - REACT_APP_API_PASS="admin123"
    ports:
      - "3000:3000"
    links : 
      - "backend"
